name: 'junito-xml'
author: 'Chris Maillefaud'
description: 'Parse and logs JUnit XML reports'
branding:
  icon: 'search'
  color: 'orange'
inputs:
  filename:
    description: 'JUnit Report filename'
    required: false
    default: 'test-report.xml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename}}
