name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip-ci')
    runs-on: ubuntu-latest
    name: Run Pre-Commit
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v3.0.0
  test:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip-ci')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.10'
      - name: Update tools
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.6
      - name: Install Project
        run: |
          make install
      - name: Run CI Tests
        run: |
          make ci
  publish:
    needs: [lint,test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.10'
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.6
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
